---
# tasks file for ansible-role-nginx-pagespeed

- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"

# Setup/install tasks.
- include: setup-RedHat.yml
  when: ansible_os_family == 'RedHat'

#- include: setup-Debian.yml
#  when: ansible_os_family == 'Debian'

- name: Create build directory
  file: path={{build_dir}} state=directory mode=0755

- include: pagespeed.yml
- include: nginx.yml
