---
- name: Download nginx
  get_url: url=http://nginx.org/download/nginx-{{nginx_version}}.tar.gz dest={{build_dir}}/nginx-{{nginx_version}}.tar.gz

#- name: Untar nginx
#  command: tar -xzvf {{build_dir}}/nginx-{{nginx_version}}.tar.gz -C {{build_dir}}

- name: Unarchive nginx
  unarchive: src={{build_dir}}/nginx-{{nginx_version}}.tar.gz dest={{build_dir}} copy=no

- name: Configure nginx
  command: >
    ./configure 
    --add-module="{{build_dir}}/ngx_pagespeed-{{nps_release}}" 
    chdir="{{build_dir}}/nginx-{{nginx_version}}"
    --user=nginx                          
    --group=nginx                         
    --prefix=/etc/nginx                   
    --sbin-path=/usr/sbin/nginx           
    --conf-path=/etc/nginx/nginx.conf     
    --pid-path=/var/run/nginx.pid         
    --lock-path=/var/run/nginx.lock       
    --error-log-path=/var/log/nginx/error.log 
    --http-log-path=/var/log/nginx/access.log 
    --with-http_gzip_static_module        
    --with-http_stub_status_module        
    --with-http_ssl_module                
    --with-pcre                           
    --with-file-aio                       
    --with-http_realip_module             
    --without-http_scgi_module            
    --without-http_uwsgi_module           
    --without-http_fastcgi_module    

- name: Make nginx
  command: make chdir="{{build_dir}}/nginx-{{nginx_version}}"

- name: Install nginx
  command: make install chdir="{{build_dir}}/nginx-{{nginx_version}}"

- name: Add nginx user
  user: name=nginx system=yes shell=/sbin/nologin 

